---
# file: roles/workstations-school/tasks/display-maanger.yml

- include: lightdm.yml 
  when: ansible_distribution != "Fedora" or ansible_distribution_major_version|int < 26
  tags:
   - install
   - display-manager
   - atomic

- include: gdm.yml
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 26
  tags:
   - install
   - display-manager
   - atomic
